export const OfrEnums = {
  filmSims: [
    'Provia',
    'Velvia',
    'Astia',
    'Classic Chrome',
    'Pro Neg. Hi',
    'Pro Neg. Std',
    'Classic Negative',
    'Eterna',
    'Eterna Bleach Bypass',
    'Nostalgic Negative',
    'Reala Ace',
    'Acros STD',
    'Acros Yellow',
    'Acros Red',
    'Acros Green',
    'Monochrome STD',
    'Monochrome Yellow',
    'Monochrome Red',
    'Monochrome Green',
    'Sepia',
  ],
  monoFilmSims: new Set([
    'Acros STD',
    'Acros Yellow',
    'Acros Red',
    'Acros Green',
    'Monochrome STD',
    'Monochrome Yellow',
    'Monochrome Red',
    'Monochrome Green',
    'Sepia',
  ]),
  wbModes: [
    'Auto',
    'Auto (white priority)',
    'Auto (ambience priority)',
    'Daylight',
    'Shade',
    'Incandescent',
    'Fluorescent 1',
    'Fluorescent 2',
    'Fluorescent 3',
    'Kelvin',
    'Underwater',
    'Custom 1',
    'Custom 2',
    'Custom 3',
  ],
  sensors: [
    'X-Trans I',
    'X-Trans II',
    'X-Trans III',
    'X-Trans IV',
    'X-Trans V',
    'GFX',
    'Bayer',
    'EXR-CMOS',
    'Full Spectrum',
  ],
  dynamicRanges: ['DR100', 'DR200', 'DR400', 'DR-Auto'],
  dRangePriorities: ['Off', 'Auto', 'Weak', 'Strong'],
  grainRoughness: ['Off', 'Weak', 'Strong'],
  grainSizes: ['Small', 'Large'],
  effects: ['Off', 'Weak', 'Strong'],
};

export const isMonoFilmSim = (name: string): boolean =>
  OfrEnums.monoFilmSims.has(name);
