/** Per-generation capability matrix shown in the admin console (read-only; the app derives real caps from the body at runtime). */
export const CAMERA_PROFILES = {
  updatedAt: '2026-08-20',
  fields: [
    'film_simulation',
    'dynamic_range',
    'd_range_priority',
    'grain_roughness',
    'grain_size',
    'color_chrome_effect',
    'color_chrome_fx_blue',
    'white_balance',
    'wb_kelvin',
    'white_balance_red',
    'white_balance_blue',
    'highlight',
    'shadow',
    'color',
    'sharpness',
    'high_iso_nr',
    'clarity',
    'monochromatic_color_warm_cool',
    'monochromatic_color_magenta_green',
    'smooth_skin_effect',
    'exposure_compensation',
    'iso',
  ],
  generations: [
    {
      id: 'X-Trans V',
      bodies: [
        'X-T5',
        'X-H2',
        'X-H2S',
        'X-S20',
        'X-T50',
        'X-M5',
        'X-E5',
        'X-T30 III',
        'X100VI',
      ],
      slots: 7,
      slotsNote: 'C1–C4 on X-S20 / X-M5',
      filmSims: 20,
      usbWrite: 'full',
      tested: ['X-S20 fw 3.30'],
      unsupported: [],
    },
    {
      id: 'GFX',
      bodies: ['GFX100 II', 'GFX100S II', 'GFX100RF'],
      slots: 7,
      filmSims: 20,
      usbWrite: 'full',
      tested: [],
      unsupported: [],
    },
    {
      id: 'X-Trans IV',
      bodies: [
        'X-T4',
        'X-S10',
        'X-Pro3',
        'X100V',
        'X-T3',
        'X-T30',
        'X-T30 II',
        'X-E4',
      ],
      slots: 7,
      slotsNote: 'C1–C4 on X-S10 / X-T30 II',
      filmSims: 18,
      usbWrite: 'probe',
      tested: [],
      unsupported: ['smooth_skin_effect'],
      note: 'Bodies may not advertise the preset properties (D18C) — app checks GetDeviceInfo at connect',
    },
    {
      id: 'X-Trans III',
      bodies: ['X-T2', 'X-Pro2', 'X-H1', 'X-T20', 'X100F', 'X-E3'],
      slots: 7,
      filmSims: 15,
      usbWrite: 'none',
      tested: [],
      unsupported: [
        'clarity',
        'color_chrome_fx_blue',
        'grain_size',
        'monochromatic_color_warm_cool',
        'monochromatic_color_magenta_green',
        'smooth_skin_effect',
      ],
    },
    {
      id: 'X-Trans II',
      bodies: ['X-T1', 'X-T10', 'X100T', 'X-E2'],
      slots: 7,
      filmSims: 11,
      usbWrite: 'none',
      tested: [],
      unsupported: [
        'clarity',
        'color_chrome_effect',
        'color_chrome_fx_blue',
        'grain_roughness',
        'grain_size',
        'd_range_priority',
        'monochromatic_color_warm_cool',
        'monochromatic_color_magenta_green',
        'smooth_skin_effect',
      ],
    },
    {
      id: 'X-Trans I',
      bodies: ['X-Pro1', 'X-E1', 'X-M1'],
      slots: 7,
      filmSims: 10,
      usbWrite: 'none',
      tested: [],
      unsupported: [
        'clarity',
        'color_chrome_effect',
        'color_chrome_fx_blue',
        'grain_roughness',
        'grain_size',
        'd_range_priority',
        'monochromatic_color_warm_cool',
        'monochromatic_color_magenta_green',
        'smooth_skin_effect',
      ],
    },
    {
      id: 'Bayer',
      bodies: ['X-T200', 'X-A7', 'XF10', 'X-T100'],
      slots: 7,
      filmSims: 11,
      usbWrite: 'none',
      tested: [],
      unsupported: [
        'clarity',
        'color_chrome_fx_blue',
        'grain_size',
        'monochromatic_color_warm_cool',
        'monochromatic_color_magenta_green',
      ],
    },
  ],
} as const;
